name: Fastlane-AutoBuild
settings:
  base:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: 'YES'
options:
  developmentLanguage: ko
  bundleIdPrefix: io.github.92pino
targets:
    Fastlane-AutoBuild:
        deploymentTarget: '13.0'
        info:
          path: Fastlane-AutoBuild/Info.plist
          properties:
            LOG_LEVEL: debug
            NETWORK_CONFIGURATION: Test
            GitHash: somehash
            CFBundleDisplayName: "Fastlane-AutoBuild"
            CFBundleIconName: Media.xcassets/AppIcon.appiconset
            CFBundleName: Fastlane-AutoBuild
            CFBundleShortVersionString: "1.0"
            CFBundleVersion: "1"
            UILaunchStoryboardName: LaunchScreen
            UISupportedInterfaceOrientations:
              - UIInterfaceOrientationLandscapeLeft
              - UIInterfaceOrientationLandscapeRight
            UIViewControllerBasedStatusBarAppearance: false
        platform: iOS
        scheme:
          gatherCoverageData: true
        settings:
          base:
            CODE_SIGN_STYLE: Automatic
            DEVELOPMENT_TEAM: VB5KPC8TUV
            PRODUCT_BUNDLE_IDENTIFIER: Fastlane-AutoBuild
            SWIFT_VERSION: 5.2
            TARGETED_DEVICE_FAMILY: 2
#        dependencies:
#            - sdk: Fastlane-AutoBuild.framework # 사용하는 framework 들 등록
        sources:
          - path: Fastlane-AutoBuild
        type: application
    Fastlane-AutoBuildTests:
        type: bundle.unit-test # 테스트 타입
        platform: iOS # 플랫폼
        sources: # 소스들 추가
            - path: Fastlane-AutoBuildTests
        info:
            path: Fastlane-AutoBuildTests/Info.plist
    Fastlane-AutoBuildUITests:
        type: bundle.ui-testing # 테스트 타입
        platform: iOS # 플랫폼
        sources: # 소스들 추가
            - path: Fastlane-AutoBuildUITests
        info:
            path: Fastlane-AutoBuildUITests/Info.plist
